// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockLens.data;

#nullable disable

namespace StockLens.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockLens.Models.Cities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("StockLens.Models.Industries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SectorId");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("StockLens.Models.Quotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("close")
                        .HasColumnType("numeric");

                    b.Property<decimal>("high")
                        .HasColumnType("numeric");

                    b.Property<decimal>("low")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("numtrades")
                        .HasColumnType("numeric");

                    b.Property<decimal>("open")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<BigInteger>("value")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("volume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("waprice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("StockLens.Models.Sectors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("StockLens.Models.Tickers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DividendsPercents")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DividendsValue")
                        .HasColumnType("numeric");

                    b.Property<int>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<int>("ListLevel")
                        .HasColumnType("integer");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Privileged")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("StockLens.Models.Industries", b =>
                {
                    b.HasOne("StockLens.Models.Sectors", "Sector")
                        .WithMany("Industries")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("StockLens.Models.Quotes", b =>
                {
                    b.HasOne("StockLens.Models.Tickers", "Ticker")
                        .WithMany("Quotation")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("StockLens.Models.Tickers", b =>
                {
                    b.HasOne("StockLens.Models.Cities", "City")
                        .WithMany("Tickers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLens.Models.Industries", "Industry")
                        .WithMany("Tickers")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("StockLens.Models.Cities", b =>
                {
                    b.Navigation("Tickers");
                });

            modelBuilder.Entity("StockLens.Models.Industries", b =>
                {
                    b.Navigation("Tickers");
                });

            modelBuilder.Entity("StockLens.Models.Sectors", b =>
                {
                    b.Navigation("Industries");
                });

            modelBuilder.Entity("StockLens.Models.Tickers", b =>
                {
                    b.Navigation("Quotation");
                });
#pragma warning restore 612, 618
        }
    }
}
